
my_program: my_program.c
	echo "Hello world make before gcc!"
	gcc -g -o my_program my_program.c
	echo "Hello world make after gcc!"

foo:
	echo "Running foo rule!"
	ls -l *.c
	date

clean:
	rm -f *.o my_program


